// Static proof bundle loaded from public/proofs.json. Generated by
// scripts/merkle.ts; committed to the repo so the claim page is fully
// static — no API server, no DB, no key material. The browser fetches
// proofs.json on page load and looks up the connected address locally.
//
// If the file is missing (e.g. local dev before snapshot has been run),
// returns an empty bundle instead of throwing — the UI shows
// "Proofs not generated yet" rather than crashing.

export interface ProofEntry {
  amount: string; // hex-encoded uint256 wei
  proof: string[]; // bytes32[] sorted-sibling Merkle proof
  index: number; // position in the leaf list (debug aid)
}

export interface ProofsBundle {
  network_chain_id: number;
  snapshot_chain_id: number;
  snapshot_height: number;
  snapshot_block_hash: string;
  merkle_root: string;
  phase_total_wei: string;
  per_wallet_wei: string;
  total_allocated_wei: string;
  dust_wei: string;
  eligible_count: number;
  allocation: string;
  entries: Record<string, ProofEntry>;
  leaf_format: string;
  contract_compatible: string;
}

export const EMPTY_BUNDLE: ProofsBundle = {
  network_chain_id: 7119,
  snapshot_chain_id: 7120,
  snapshot_height: 0,
  snapshot_block_hash: "0x0",
  merkle_root: "0x0000000000000000000000000000000000000000000000000000000000000000",
  phase_total_wei: "0",
  per_wallet_wei: "0",
  total_allocated_wei: "0",
  dust_wei: "0",
  eligible_count: 0,
  allocation: "flat",
  entries: {},
  leaf_format: "keccak256(abi.encodePacked(address, uint256))",
  contract_compatible: "MerkleAirdrop.sol — sentrix-labs/canonical-contracts",
};

// Client-only fetch helper. Server components in app/ load proofs.json
// directly via Node fs (see lib/proofs-server.ts) so the file is read at
// build / request time without shipping a 1-3 MB JSON to every browser.
export async function fetchProofsClient(): Promise<ProofsBundle> {
  try {
    const res = await fetch("/proofs.json", { cache: "force-cache" });
    if (!res.ok) return EMPTY_BUNDLE;
    return (await res.json()) as ProofsBundle;
  } catch {
    return EMPTY_BUNDLE;
  }
}

export function lookupEntry(bundle: ProofsBundle, address: string): ProofEntry | null {
  if (!address) return null;
  return bundle.entries[address.toLowerCase()] ?? null;
}
